<?php

$messages = array(
    "Action" => "Action",
    "Add" => "Add",
    "Cancel" => "Batal",
    "Create" => "Tambah",
    "Delete" => "Delete",
    "DeleteConfirmation" => "Delete confirmation",
    "Edit" => "Edit",
    "Msg_DeleteConfirmation" => "Are you sure want to delete {0} '{1}'?",
    "Msg_InvalidCreateAttempt" => "The {0} cannot be created because it already exists.",
    "Msg_InvalidEmail" => "{0} harus memiliki format email yang valid.",
    "Msg_InvalidUpdateAttempt" => "The {0} cannot be updated because it already exists.",
    "Msg_NotMatch" => "{0} tidak sesuai.",
    "Msg_PresenceOf" => "The field {0} is mandatory.",
    "Msg_Required" => "{0} harus diisi.",
    "Msg_SuccessfullyCreated" => "{0} '{1}' was created successfully.",
    "Msg_SuccessfullyDeleted" => "{0} '{1}' was deleted successfully.",
    "Msg_SuccessfullyUpdated" => "{0} '{1}' was updated successfully.",
    "Msg_TooLong" => "{0} terlalu panjang.",
    "Msg_TooShort" => "{0} terlalu pendek.",
    "Msg_Uniqueness" => "Maaf, {0} '{1}' sudah terdaftar.",
    "Name" => "Name",
    "NotFound" => "{0} not found.",
    "Reload" => "Reload",
    "Submit" => "Kirim",
    "User" => "User",
    "Users" => "Users",
);